server:
  port: ${APP_PORT:8083}

spring:
  config:
    use-legacy-processing: true
  profiles:
    active: local
  activemq:
    broker-url: "tcp://localhost:61616"
    password: admin
    user: admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: default

logging:
  level:
    ROOT: INFO
    ru.tsedrik: DEBUG
    org.springframework: INFO
    org.springframework.security: INFO
    ru.tsedrik.aspect: DEBUG
  appenders:
    console:
      enabled: true
    file:
      enabled: true
      maxHistory: 1000

sc:
  kafka:
    user:
      send-topic: "sc.kafka.user.out"
      receive-topic: "sc.kafka.user.in"
