server:
  port: ${APP_PORT:8080}
  servlet:
    session:
      cookie:
        http-only: true
    context-path: /snowboard-courses
    application-display-name: SnowboardCourses
  tomcat:
    max-connections: 1000
    accept-count: 100
    connection-timeout: 30000

spring:
  application:
    name: snowboard-courses
    token:
      key: 84FiStd1PDDkXOfAHgfPxCC7xThp7QrGs9Xpy9QUTWU=
      lifetime: 3600000
      issuer: snowboard-courses-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/changelog-master.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: false
    hibernate:
      hbm2ddl:
        auto: none
      default_schema: sc_core
      use_sql_comments: true
      format_sql: true
  quartz:
    auto-startup: true
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      #       Передача управления транзакциями в quartz. Не использовать при JTA.
      org.quartz.jobStore.class: org.quartz.impl.jdbcjobstore.JobStoreTX
      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
      #       Настройка используется если запущено больше 1 экземпляра quartz
      org.quartz.jobStore.isClustered: true
      #       Максимальное количество тригеров обработанных за 1 раз. Не делать больше 20(по умолчанию).
      org.quartz.jobStore.maxMisfiresToHandleAtATime: 1
      org.quartz.threadPool.class: org.quartz.simpl.SimpleThreadPool
      #       Количество запущенных воркеров для выполнения задач на текущей ноде
      org.quartz.threadPool.threadCount: 2
      org.quartz.threadPool.threadsInheritContextClassLoaderOfInitializingThread: true
      org.quartz.scheduler.instanceName: snowboard-courses-quartz
      org.quartz.scheduler.instanceId: AUTO

logging:
  level:
    ROOT: INFO
    ru.tsedrik: DEBUG
    org.springframework: INFO
    org.hibernate:
      SQL: DEBUG
      type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: info, health, metrics
  metrics:
    export:
      atlas:
        enabled: true

course:
  maxGroupCount: 2
group:
  maxPersonPerGroup: 2

swagger:
  title: Snowboard Courses
  description: API для проекта
  contact:
    mail: tsedrik@i-teco.ru
    name: Наталья Ц
    url: http://iteco.ru

scheduling:
  cron:
    enabled: true
    updating-course-status:
      expression: "* * 00 ? * *"
